### PR TITLE
Added a profile for Erik Thiart

### PR DESCRIPTION
**Pull request by ErikThiart**
I added a file for Erik Thiart to the repo.

### CODE REVIEW

**Comment by Vulcanit3** [comment]
:+1:  Happy to merge, do you not also want to add yourself to the main readme.md?

**Comment by ErikThiart** [comment]
> 👍 Happy to merge, do you not also want to add yourself to the main readme.md?

Yes please, figured I will add the people's page first to test the waters and then go edit the readme upon success of this merge.

**Comment by Vulcanit3** [comment]
> > +1 Happy to merge, do you not also want to add yourself to the main readme.md?
> 
> Yes please, figured I will add the people's page first to test the waters and then go edit the readme upon success of this merge.

Cool, from my side I think it makes sense to just add a commit to this PR for it.

I'll push it through as 1 merge then :+1:

**Comment by ChristianWitts** [comment]
There's a convenience script `add_self.sh` that can be run to add you to the `README` and create the scaffold `people/` file for you to fill in.

Looks good, if you can just add yourself to the `People` table, and we can merge it.

**Pull request merged**
