### PR TITLE
Adding timhaak

### PR DESCRIPTION
**Pull request by timhaak**
Just adding my self

### CODE REVIEW

**Comment by timhaak** [comment]
Meh, I see it added my second commit where I tried to separate the expanding the script. 

Shout if this is a problem and I'll do the one.

Wait for the merge then do the other.

Also, shout if you want any specific changes to the script bit.

**Review by JohnRoux — APPROVED** [review]
Not sure about the editorconfig, but otherwise looks good to me :+1:

**Comment by JohnRoux** [comment]
The script bit looks cool (I haven't tested it though)
I'm not convinced about all the extra inputs (linkedin/cell etc)
As long as they're optional it's not a biggie though, thanks :)

**Comment by timhaak** [comment]
Agree it needs a bit more though need some time to think of the best way to do it.

Not sure a shell script is the best option so we can let people pick what they want.

But will think and when I'm bored and feel like playing will try to make something better.

**Comment by ChristianWitts** [comment]
I originally made the shell script for consistency of the `README.md`, as well as portability between _all_ the OSs.

**Comment by timhaak** [comment]
Yes assumed something like that :).

More trying to think of how to build something that allows more tuning.

Please don't take my comment as criticism more as a though for something fun for me to do :)

Possibly thinking something like go (mainly to play :) )

I've wanted to play with this for quite a while https://github.com/gizak/termui .

If for myself I would have used https://github.com/yaronn/blessed-contrib as only played with go very briefly.

Or I might finally try out rust https://github.com/fdehau/tui-rs though not sure how good it's cross-compile is.

I know go's is really simple to do.

**Comment by JohnRoux** [comment]
Tbh, if it get's used by maybe one person every 2 months that's cool.
It's a value add, nothing's stopping peeps from just editing the files themselves :shrug: 

So yeah, I'm really not phased about adding much to it. I think it's a cool add on as it is

**Comment by JohnRoux** [comment]
The main value is actually in the alpha ordering of the names in the readme.md :joy:

**Comment by timhaak** [comment]
Yes, that was the only thing I wasn't sure about.

Also which setting you preferred.

Decided to add then you could change to your preferred settings as most of the work would be done.

Always a fan of trying to keep things consistent and having the tools auto changed to the preferred settings :)

**Pull request merged**
